image: gradle:4.4.1-jdk8

stages:
  - build

job:
  stage: build
  script:
    - gradle clean build
  artifacts:
    name: Impactor-${CI_COMMIT_REF_NAME}
    paths:
      - build/libs
  tags:
    - build
